package com.java.src.lululu.business.service;


import com.java.src.lululu.business.repository.LwAccountRepository;

import lombok.extern.slf4j.Slf4j;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;


/**
 * This class is generated by jOOQ.
 */
@Slf4j
@Service
public class LwAccountService  {

    @Autowired
    private LwAccountRepository lwAccountRepository;

}
