package com.java.src.lululu.business.service;


import com.java.src.lululu.business.repository.LwMemberCardRepository;

import lombok.extern.slf4j.Slf4j;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;


/**
 * This class is generated by jOOQ.
 */
@Slf4j
@Service
public class LwMemberCardService  {

    @Autowired
    private LwMemberCardRepository lwMemberCardRepository;

}
