/*
 * This file is generated by jOOQ.
*/
package com.java.src.lululu.business.domain.tables;


import com.java.src.lululu.business.domain.Keys;
import com.java.src.lululu.business.domain.Lw;
import com.java.src.lululu.business.domain.tables.records.LwGoodsRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LwGoods extends TableImpl<LwGoodsRecord> {

    private static final long serialVersionUID = 305193476;

    /**
     * The reference instance of <code>LW.lw_goods</code>
     */
    public static final LwGoods LW_GOODS = new LwGoods();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LwGoodsRecord> getRecordType() {
        return LwGoodsRecord.class;
    }

    /**
     * The column <code>LW.lw_goods.id</code>.
     */
    public final TableField<LwGoodsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>LW.lw_goods.create_date</code>. 创建时间
     */
    public final TableField<LwGoodsRecord, Timestamp> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>LW.lw_goods.update_date</code>. 更新时间
     */
    public final TableField<LwGoodsRecord, Timestamp> UPDATE_DATE = createField("update_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");

    /**
     * The column <code>LW.lw_goods.remarks</code>. 备注信息
     */
    public final TableField<LwGoodsRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "备注信息");

    /**
     * The column <code>LW.lw_goods.del_flag</code>. 逻辑删除标记（0：显示；1：隐藏）
     */
    public final TableField<LwGoodsRecord, UInteger> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "逻辑删除标记（0：显示；1：隐藏）");

    /**
     * The column <code>LW.lw_goods.shop_id</code>.
     */
    public final TableField<LwGoodsRecord, Long> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>LW.lw_goods.goods_name</code>. 商品名
     */
    public final TableField<LwGoodsRecord, String> GOODS_NAME = createField("goods_name", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "商品名");

    /**
     * The column <code>LW.lw_goods.price</code>. 商品单价
     */
    public final TableField<LwGoodsRecord, BigDecimal> PRICE = createField("price", org.jooq.impl.SQLDataType.DECIMAL.precision(20, 4), this, "商品单价");

    /**
     * The column <code>LW.lw_goods.integral</code>. 返用积分
     */
    public final TableField<LwGoodsRecord, Integer> INTEGRAL = createField("integral", org.jooq.impl.SQLDataType.INTEGER, this, "返用积分");

    /**
     * The column <code>LW.lw_goods.state</code>.
     */
    public final TableField<LwGoodsRecord, Integer> STATE = createField("state", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>LW.lw_goods</code> table reference
     */
    public LwGoods() {
        this("lw_goods", null);
    }

    /**
     * Create an aliased <code>LW.lw_goods</code> table reference
     */
    public LwGoods(String alias) {
        this(alias, LW_GOODS);
    }

    private LwGoods(String alias, Table<LwGoodsRecord> aliased) {
        this(alias, aliased, null);
    }

    private LwGoods(String alias, Table<LwGoodsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lw.LW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LwGoodsRecord> getPrimaryKey() {
        return Keys.KEY_LW_GOODS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LwGoodsRecord>> getKeys() {
        return Arrays.<UniqueKey<LwGoodsRecord>>asList(Keys.KEY_LW_GOODS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwGoods as(String alias) {
        return new LwGoods(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LwGoods rename(String name) {
        return new LwGoods(name, null);
    }
}
