/*
 * This file is generated by jOOQ.
*/
package com.java.src.lululu.business.domain.tables;


import com.java.src.lululu.business.domain.Keys;
import com.java.src.lululu.business.domain.Lw;
import com.java.src.lululu.business.domain.tables.records.LwShopRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LwShop extends TableImpl<LwShopRecord> {

    private static final long serialVersionUID = 1741773254;

    /**
     * The reference instance of <code>LW.lw_shop</code>
     */
    public static final LwShop LW_SHOP = new LwShop();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LwShopRecord> getRecordType() {
        return LwShopRecord.class;
    }

    /**
     * The column <code>LW.lw_shop.id</code>.
     */
    public final TableField<LwShopRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>LW.lw_shop.create_date</code>. 创建时间
     */
    public final TableField<LwShopRecord, Timestamp> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "创建时间");

    /**
     * The column <code>LW.lw_shop.update_date</code>. 更新时间
     */
    public final TableField<LwShopRecord, Timestamp> UPDATE_DATE = createField("update_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");

    /**
     * The column <code>LW.lw_shop.remarks</code>. 备注信息
     */
    public final TableField<LwShopRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "备注信息");

    /**
     * The column <code>LW.lw_shop.del_flag</code>. 逻辑删除标记（0：显示；1：隐藏）
     */
    public final TableField<LwShopRecord, UInteger> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "逻辑删除标记（0：显示；1：隐藏）");

    /**
     * The column <code>LW.lw_shop.name</code>. 店名
     */
    public final TableField<LwShopRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "店名");

    /**
     * The column <code>LW.lw_shop.address</code>. 地址
     */
    public final TableField<LwShopRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "地址");

    /**
     * The column <code>LW.lw_shop.contact_number</code>. 联系电话
     */
    public final TableField<LwShopRecord, String> CONTACT_NUMBER = createField("contact_number", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "联系电话");

    /**
     * Create a <code>LW.lw_shop</code> table reference
     */
    public LwShop() {
        this("lw_shop", null);
    }

    /**
     * Create an aliased <code>LW.lw_shop</code> table reference
     */
    public LwShop(String alias) {
        this(alias, LW_SHOP);
    }

    private LwShop(String alias, Table<LwShopRecord> aliased) {
        this(alias, aliased, null);
    }

    private LwShop(String alias, Table<LwShopRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lw.LW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LwShopRecord> getPrimaryKey() {
        return Keys.KEY_LW_SHOP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LwShopRecord>> getKeys() {
        return Arrays.<UniqueKey<LwShopRecord>>asList(Keys.KEY_LW_SHOP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwShop as(String alias) {
        return new LwShop(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LwShop rename(String name) {
        return new LwShop(name, null);
    }
}
