package com.java.src.lululu.business.repository;


import com.java.src.lululu.business.domain.tables.records.LwGoodsRecord;
import com.java.src.lululu.business.pojo.LwGoodsPojo;
import com.java.src.lululu.business.repository.AbstractCRUDRepository;

import lombok.extern.slf4j.Slf4j;

import org.jooq.DSLContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import static com.java.src.lululu.business.domain.Tables.*;
/**
 * This class is generated by jOOQ.
 */
@Slf4j
@Repository
public class LwGoodsRepository extends AbstractCRUDRepository<LwGoodsRecord, Long, LwGoodsPojo> {

    @Autowired
    public LwGoodsRepository(DSLContext dslContext) {
        super(dslContext, LW_GOODS, LW_GOODS.ID, LwGoodsPojo.class);
    }

    public int updateGoodsName(Long id,String goodsName){
        return dslContext.update(LW_GOODS)
                .set(LW_GOODS.GOODS_NAME,goodsName)
                .where(LW_GOODS.ID.eq(id))
                .execute();
    }
}
