package com.java.src.lululu.business.repository;


import com.java.src.lululu.business.domain.tables.records.LwMemberCardRecord;
import com.java.src.lululu.business.pojo.LwMemberCardPojo;
import com.java.src.lululu.business.repository.AbstractCRUDRepository;

import lombok.extern.slf4j.Slf4j;

import org.jooq.DSLContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import static com.java.src.lululu.business.domain.Tables.*;
/**
 * This class is generated by jOOQ.
 */
@Slf4j
@Repository
public class LwMemberCardRepository extends AbstractCRUDRepository<LwMemberCardRecord, Long, LwMemberCardPojo> {

    @Autowired
    public LwMemberCardRepository(DSLContext dslContext) {
        super(dslContext, LW_MEMBER_CARD, LW_MEMBER_CARD.ID, LwMemberCardPojo.class);
    }
}
