package com.java.src.lululu.business.repository;


import com.java.src.lululu.business.domain.tables.records.LwMemberRecord;
import com.java.src.lululu.business.pojo.LwMemberPojo;
import com.java.src.lululu.business.repository.AbstractCRUDRepository;

import lombok.extern.slf4j.Slf4j;

import org.jooq.DSLContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import static com.java.src.lululu.business.domain.Tables.*;
/**
 * This class is generated by jOOQ.
 */
@Slf4j
@Repository
public class LwMemberRepository extends AbstractCRUDRepository<LwMemberRecord, Long, LwMemberPojo> {

    @Autowired
    public LwMemberRepository(DSLContext dslContext) {
        super(dslContext, LW_MEMBER, LW_MEMBER.ID, LwMemberPojo.class);
    }
}
