package com.java.src.lululu.business.repository;


import com.java.src.lululu.business.domain.tables.records.LwOrderRecord;
import com.java.src.lululu.business.pojo.LwOrderPojo;
import com.java.src.lululu.business.repository.AbstractCRUDRepository;

import lombok.extern.slf4j.Slf4j;

import org.jooq.DSLContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import static com.java.src.lululu.business.domain.Tables.*;
/**
 * This class is generated by jOOQ.
 */
@Slf4j
@Repository
public class LwOrderRepository extends AbstractCRUDRepository<LwOrderRecord, Long, LwOrderPojo> {

    @Autowired
    public LwOrderRepository(DSLContext dslContext) {
        super(dslContext, LW_ORDER, LW_ORDER.ID, LwOrderPojo.class);
    }
}
