package com.java.src.lululu.business.repository;


import com.java.src.lululu.business.domain.tables.records.LwShopRecord;
import com.java.src.lululu.business.pojo.LwShopPojo;
import com.java.src.lululu.business.repository.AbstractCRUDRepository;

import lombok.extern.slf4j.Slf4j;

import org.jooq.DSLContext;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import static com.java.src.lululu.business.domain.Tables.*;
/**
 * This class is generated by jOOQ.
 */
@Slf4j
@Repository
public class LwShopRepository extends AbstractCRUDRepository<LwShopRecord, Long, LwShopPojo> {

    @Autowired
    public LwShopRepository(DSLContext dslContext) {
        super(dslContext, LW_SHOP, LW_SHOP.ID, LwShopPojo.class);
    }
}
