/*
 * This file is generated by jOOQ.
*/
package com.java.src.lululu.business.domain.tables.records;


import com.java.src.lululu.business.domain.tables.LwMember;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LwMemberRecord extends UpdatableRecordImpl<LwMemberRecord> implements Record12<Long, Timestamp, Timestamp, String, UInteger, String, String, String, Integer, String, Date, Long> {

    private static final long serialVersionUID = -160085177;

    /**
     * Setter for <code>LW.lw_member.id</code>.
     */
    public LwMemberRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LW.lw_member.create_date</code>. 创建时间
     */
    public LwMemberRecord setCreateDate(Timestamp value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>LW.lw_member.update_date</code>. 更新时间
     */
    public LwMemberRecord setUpdateDate(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member.update_date</code>. 更新时间
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>LW.lw_member.remarks</code>. 备注信息
     */
    public LwMemberRecord setRemarks(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member.remarks</code>. 备注信息
     */
    public String getRemarks() {
        return (String) get(3);
    }

    /**
     * Setter for <code>LW.lw_member.del_flag</code>. 逻辑删除标记（0：显示；1：隐藏）
     */
    public LwMemberRecord setDelFlag(UInteger value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member.del_flag</code>. 逻辑删除标记（0：显示；1：隐藏）
     */
    public UInteger getDelFlag() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>LW.lw_member.name</code>. 姓名
     */
    public LwMemberRecord setName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member.name</code>. 姓名
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>LW.lw_member.mobile</code>. 电话
     */
    public LwMemberRecord setMobile(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member.mobile</code>. 电话
     */
    public String getMobile() {
        return (String) get(6);
    }

    /**
     * Setter for <code>LW.lw_member.photo</code>. 照片
     */
    public LwMemberRecord setPhoto(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member.photo</code>. 照片
     */
    public String getPhoto() {
        return (String) get(7);
    }

    /**
     * Setter for <code>LW.lw_member.sex</code>. 性别
     */
    public LwMemberRecord setSex(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member.sex</code>. 性别
     */
    public Integer getSex() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>LW.lw_member.address</code>. 地址
     */
    public LwMemberRecord setAddress(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member.address</code>. 地址
     */
    public String getAddress() {
        return (String) get(9);
    }

    /**
     * Setter for <code>LW.lw_member.birthday</code>.
     */
    public LwMemberRecord setBirthday(Date value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member.birthday</code>.
     */
    public Date getBirthday() {
        return (Date) get(10);
    }

    /**
     * Setter for <code>LW.lw_member.shop_id</code>.
     */
    public LwMemberRecord setShopId(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member.shop_id</code>.
     */
    public Long getShopId() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Timestamp, Timestamp, String, UInteger, String, String, String, Integer, String, Date, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Timestamp, Timestamp, String, UInteger, String, String, String, Integer, String, Date, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return LwMember.LW_MEMBER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return LwMember.LW_MEMBER.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return LwMember.LW_MEMBER.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return LwMember.LW_MEMBER.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return LwMember.LW_MEMBER.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return LwMember.LW_MEMBER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return LwMember.LW_MEMBER.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return LwMember.LW_MEMBER.PHOTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return LwMember.LW_MEMBER.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return LwMember.LW_MEMBER.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field11() {
        return LwMember.LW_MEMBER.BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return LwMember.LW_MEMBER.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value11() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord value2(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord value3(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord value4(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord value5(UInteger value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord value6(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord value7(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord value8(String value) {
        setPhoto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord value9(Integer value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord value10(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord value11(Date value) {
        setBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord value12(Long value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberRecord values(Long value1, Timestamp value2, Timestamp value3, String value4, UInteger value5, String value6, String value7, String value8, Integer value9, String value10, Date value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LwMemberRecord
     */
    public LwMemberRecord() {
        super(LwMember.LW_MEMBER);
    }

    /**
     * Create a detached, initialised LwMemberRecord
     */
    public LwMemberRecord(Long id, Timestamp createDate, Timestamp updateDate, String remarks, UInteger delFlag, String name, String mobile, String photo, Integer sex, String address, Date birthday, Long shopId) {
        super(LwMember.LW_MEMBER);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, remarks);
        set(4, delFlag);
        set(5, name);
        set(6, mobile);
        set(7, photo);
        set(8, sex);
        set(9, address);
        set(10, birthday);
        set(11, shopId);
    }
}
