/*
 * This file is generated by jOOQ.
*/
package com.java.src.lululu.business.domain.tables.records;


import com.java.src.lululu.business.domain.tables.LwMemberCard;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LwMemberCardRecord extends UpdatableRecordImpl<LwMemberCardRecord> implements Record11<Long, Timestamp, Timestamp, String, UInteger, Long, Long, String, BigDecimal, Integer, Byte> {

    private static final long serialVersionUID = -1162022987;

    /**
     * Setter for <code>LW.lw_member_card.id</code>.
     */
    public LwMemberCardRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member_card.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LW.lw_member_card.create_date</code>. 创建时间
     */
    public LwMemberCardRecord setCreateDate(Timestamp value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member_card.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>LW.lw_member_card.update_date</code>. 更新时间
     */
    public LwMemberCardRecord setUpdateDate(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member_card.update_date</code>. 更新时间
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>LW.lw_member_card.remarks</code>. 备注信息
     */
    public LwMemberCardRecord setRemarks(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member_card.remarks</code>. 备注信息
     */
    public String getRemarks() {
        return (String) get(3);
    }

    /**
     * Setter for <code>LW.lw_member_card.del_flag</code>. 逻辑删除标记（0：显示；1：隐藏）
     */
    public LwMemberCardRecord setDelFlag(UInteger value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member_card.del_flag</code>. 逻辑删除标记（0：显示；1：隐藏）
     */
    public UInteger getDelFlag() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>LW.lw_member_card.shop_id</code>.
     */
    public LwMemberCardRecord setShopId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member_card.shop_id</code>.
     */
    public Long getShopId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>LW.lw_member_card.member_id</code>. 会员id
     */
    public LwMemberCardRecord setMemberId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member_card.member_id</code>. 会员id
     */
    public Long getMemberId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>LW.lw_member_card.card_no</code>. 会员卡号
     */
    public LwMemberCardRecord setCardNo(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member_card.card_no</code>. 会员卡号
     */
    public String getCardNo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>LW.lw_member_card.money</code>. 余额
     */
    public LwMemberCardRecord setMoney(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member_card.money</code>. 余额
     */
    public BigDecimal getMoney() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>LW.lw_member_card.integral</code>. 积分
     */
    public LwMemberCardRecord setIntegral(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member_card.integral</code>. 积分
     */
    public Integer getIntegral() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>LW.lw_member_card.state</code>. 状态  预留字段
     */
    public LwMemberCardRecord setState(Byte value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_member_card.state</code>. 状态  预留字段
     */
    public Byte getState() {
        return (Byte) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Timestamp, Timestamp, String, UInteger, Long, Long, String, BigDecimal, Integer, Byte> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Timestamp, Timestamp, String, UInteger, Long, Long, String, BigDecimal, Integer, Byte> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return LwMemberCard.LW_MEMBER_CARD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return LwMemberCard.LW_MEMBER_CARD.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return LwMemberCard.LW_MEMBER_CARD.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return LwMemberCard.LW_MEMBER_CARD.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return LwMemberCard.LW_MEMBER_CARD.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return LwMemberCard.LW_MEMBER_CARD.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return LwMemberCard.LW_MEMBER_CARD.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return LwMemberCard.LW_MEMBER_CARD.CARD_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return LwMemberCard.LW_MEMBER_CARD.MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return LwMemberCard.LW_MEMBER_CARD.INTEGRAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field11() {
        return LwMemberCard.LW_MEMBER_CARD.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCardNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getIntegral();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value11() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberCardRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberCardRecord value2(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberCardRecord value3(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberCardRecord value4(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberCardRecord value5(UInteger value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberCardRecord value6(Long value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberCardRecord value7(Long value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberCardRecord value8(String value) {
        setCardNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberCardRecord value9(BigDecimal value) {
        setMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberCardRecord value10(Integer value) {
        setIntegral(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberCardRecord value11(Byte value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwMemberCardRecord values(Long value1, Timestamp value2, Timestamp value3, String value4, UInteger value5, Long value6, Long value7, String value8, BigDecimal value9, Integer value10, Byte value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LwMemberCardRecord
     */
    public LwMemberCardRecord() {
        super(LwMemberCard.LW_MEMBER_CARD);
    }

    /**
     * Create a detached, initialised LwMemberCardRecord
     */
    public LwMemberCardRecord(Long id, Timestamp createDate, Timestamp updateDate, String remarks, UInteger delFlag, Long shopId, Long memberId, String cardNo, BigDecimal money, Integer integral, Byte state) {
        super(LwMemberCard.LW_MEMBER_CARD);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, remarks);
        set(4, delFlag);
        set(5, shopId);
        set(6, memberId);
        set(7, cardNo);
        set(8, money);
        set(9, integral);
        set(10, state);
    }
}
