/*
 * This file is generated by jOOQ.
*/
package com.java.src.lululu.business.domain.tables.records;


import com.java.src.lululu.business.domain.tables.LwOrder;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LwOrderRecord extends UpdatableRecordImpl<LwOrderRecord> implements Record22<Long, Timestamp, Timestamp, String, UInteger, String, BigDecimal, BigDecimal, Integer, Integer, Timestamp, Integer, Integer, Long, Long, Integer, Long, Long, Integer, Integer, String, BigDecimal> {

    private static final long serialVersionUID = -1856443269;

    /**
     * Setter for <code>LW.lw_order.id</code>.
     */
    public LwOrderRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LW.lw_order.create_date</code>. 创建时间
     */
    public LwOrderRecord setCreateDate(Timestamp value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>LW.lw_order.update_date</code>. 更新时间
     */
    public LwOrderRecord setUpdateDate(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.update_date</code>. 更新时间
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>LW.lw_order.remarks</code>. 备注信息
     */
    public LwOrderRecord setRemarks(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.remarks</code>. 备注信息
     */
    public String getRemarks() {
        return (String) get(3);
    }

    /**
     * Setter for <code>LW.lw_order.del_flag</code>. 逻辑删除标记（0：显示；1：隐藏）
     */
    public LwOrderRecord setDelFlag(UInteger value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.del_flag</code>. 逻辑删除标记（0：显示；1：隐藏）
     */
    public UInteger getDelFlag() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>LW.lw_order.order_no</code>. 订单号
     */
    public LwOrderRecord setOrderNo(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.order_no</code>. 订单号
     */
    public String getOrderNo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>LW.lw_order.order_money</code>. 订单金额
     */
    public LwOrderRecord setOrderMoney(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.order_money</code>. 订单金额
     */
    public BigDecimal getOrderMoney() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>LW.lw_order.pay_money</code>. 实际支付金额
     */
    public LwOrderRecord setPayMoney(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.pay_money</code>. 实际支付金额
     */
    public BigDecimal getPayMoney() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>LW.lw_order.pay_way</code>. 支付方式  现金  支付宝  微信。。。
     */
    public LwOrderRecord setPayWay(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.pay_way</code>. 支付方式  现金  支付宝  微信。。。
     */
    public Integer getPayWay() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>LW.lw_order.pay_type</code>. 支付类型   线上  线下
     */
    public LwOrderRecord setPayType(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.pay_type</code>. 支付类型   线上  线下
     */
    public Integer getPayType() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>LW.lw_order.pay_time</code>. 支付时间
     */
    public LwOrderRecord setPayTime(Timestamp value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.pay_time</code>. 支付时间
     */
    public Timestamp getPayTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>LW.lw_order.order_status</code>. 订单状态
     */
    public LwOrderRecord setOrderStatus(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.order_status</code>. 订单状态
     */
    public Integer getOrderStatus() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>LW.lw_order.pay_status</code>. 支付状态
     */
    public LwOrderRecord setPayStatus(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.pay_status</code>. 支付状态
     */
    public Integer getPayStatus() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>LW.lw_order.account_id</code>.
     */
    public LwOrderRecord setAccountId(Long value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>LW.lw_order.member_id</code>. 用户id
     */
    public LwOrderRecord setMemberId(Long value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.member_id</code>. 用户id
     */
    public Long getMemberId() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>LW.lw_order.order_type</code>. 订单类型  消费  充值
     */
    public LwOrderRecord setOrderType(Integer value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.order_type</code>. 订单类型  消费  充值
     */
    public Integer getOrderType() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>LW.lw_order.shop_id</code>.
     */
    public LwOrderRecord setShopId(Long value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.shop_id</code>.
     */
    public Long getShopId() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>LW.lw_order.goods_id</code>. 商品id
     */
    public LwOrderRecord setGoodsId(Long value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.goods_id</code>. 商品id
     */
    public Long getGoodsId() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>LW.lw_order.integral</code>. 返用积分
     */
    public LwOrderRecord setIntegral(Integer value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.integral</code>. 返用积分
     */
    public Integer getIntegral() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>LW.lw_order.goods_count</code>.
     */
    public LwOrderRecord setGoodsCount(Integer value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.goods_count</code>.
     */
    public Integer getGoodsCount() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>LW.lw_order.goods_name</code>.
     */
    public LwOrderRecord setGoodsName(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.goods_name</code>.
     */
    public String getGoodsName() {
        return (String) get(20);
    }

    /**
     * Setter for <code>LW.lw_order.goods_price</code>.
     */
    public LwOrderRecord setGoodsPrice(BigDecimal value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_order.goods_price</code>.
     */
    public BigDecimal getGoodsPrice() {
        return (BigDecimal) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Long, Timestamp, Timestamp, String, UInteger, String, BigDecimal, BigDecimal, Integer, Integer, Timestamp, Integer, Integer, Long, Long, Integer, Long, Long, Integer, Integer, String, BigDecimal> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Long, Timestamp, Timestamp, String, UInteger, String, BigDecimal, BigDecimal, Integer, Integer, Timestamp, Integer, Integer, Long, Long, Integer, Long, Long, Integer, Integer, String, BigDecimal> valuesRow() {
        return (Row22) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return LwOrder.LW_ORDER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return LwOrder.LW_ORDER.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return LwOrder.LW_ORDER.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return LwOrder.LW_ORDER.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return LwOrder.LW_ORDER.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return LwOrder.LW_ORDER.ORDER_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return LwOrder.LW_ORDER.ORDER_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return LwOrder.LW_ORDER.PAY_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return LwOrder.LW_ORDER.PAY_WAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return LwOrder.LW_ORDER.PAY_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return LwOrder.LW_ORDER.PAY_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return LwOrder.LW_ORDER.ORDER_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return LwOrder.LW_ORDER.PAY_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return LwOrder.LW_ORDER.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field15() {
        return LwOrder.LW_ORDER.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return LwOrder.LW_ORDER.ORDER_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field17() {
        return LwOrder.LW_ORDER.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field18() {
        return LwOrder.LW_ORDER.GOODS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field19() {
        return LwOrder.LW_ORDER.INTEGRAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field20() {
        return LwOrder.LW_ORDER.GOODS_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field21() {
        return LwOrder.LW_ORDER.GOODS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field22() {
        return LwOrder.LW_ORDER.GOODS_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getOrderNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getOrderMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getPayMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPayWay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getPayType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getPayTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getOrderStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getPayStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value15() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getOrderType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value17() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value18() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value19() {
        return getIntegral();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value20() {
        return getGoodsCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value21() {
        return getGoodsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value22() {
        return getGoodsPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value2(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value3(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value4(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value5(UInteger value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value6(String value) {
        setOrderNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value7(BigDecimal value) {
        setOrderMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value8(BigDecimal value) {
        setPayMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value9(Integer value) {
        setPayWay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value10(Integer value) {
        setPayType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value11(Timestamp value) {
        setPayTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value12(Integer value) {
        setOrderStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value13(Integer value) {
        setPayStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value14(Long value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value15(Long value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value16(Integer value) {
        setOrderType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value17(Long value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value18(Long value) {
        setGoodsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value19(Integer value) {
        setIntegral(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value20(Integer value) {
        setGoodsCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value21(String value) {
        setGoodsName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord value22(BigDecimal value) {
        setGoodsPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwOrderRecord values(Long value1, Timestamp value2, Timestamp value3, String value4, UInteger value5, String value6, BigDecimal value7, BigDecimal value8, Integer value9, Integer value10, Timestamp value11, Integer value12, Integer value13, Long value14, Long value15, Integer value16, Long value17, Long value18, Integer value19, Integer value20, String value21, BigDecimal value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LwOrderRecord
     */
    public LwOrderRecord() {
        super(LwOrder.LW_ORDER);
    }

    /**
     * Create a detached, initialised LwOrderRecord
     */
    public LwOrderRecord(Long id, Timestamp createDate, Timestamp updateDate, String remarks, UInteger delFlag, String orderNo, BigDecimal orderMoney, BigDecimal payMoney, Integer payWay, Integer payType, Timestamp payTime, Integer orderStatus, Integer payStatus, Long accountId, Long memberId, Integer orderType, Long shopId, Long goodsId, Integer integral, Integer goodsCount, String goodsName, BigDecimal goodsPrice) {
        super(LwOrder.LW_ORDER);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, remarks);
        set(4, delFlag);
        set(5, orderNo);
        set(6, orderMoney);
        set(7, payMoney);
        set(8, payWay);
        set(9, payType);
        set(10, payTime);
        set(11, orderStatus);
        set(12, payStatus);
        set(13, accountId);
        set(14, memberId);
        set(15, orderType);
        set(16, shopId);
        set(17, goodsId);
        set(18, integral);
        set(19, goodsCount);
        set(20, goodsName);
        set(21, goodsPrice);
    }
}
