/*
 * This file is generated by jOOQ.
*/
package com.java.src.lululu.business.domain.tables.records;


import com.java.src.lululu.business.domain.tables.LwShop;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LwShopRecord extends UpdatableRecordImpl<LwShopRecord> implements Record8<Long, Timestamp, Timestamp, String, UInteger, String, String, String> {

    private static final long serialVersionUID = 1565410025;

    /**
     * Setter for <code>LW.lw_shop.id</code>.
     */
    public LwShopRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_shop.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LW.lw_shop.create_date</code>. 创建时间
     */
    public LwShopRecord setCreateDate(Timestamp value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_shop.create_date</code>. 创建时间
     */
    public Timestamp getCreateDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>LW.lw_shop.update_date</code>. 更新时间
     */
    public LwShopRecord setUpdateDate(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_shop.update_date</code>. 更新时间
     */
    public Timestamp getUpdateDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>LW.lw_shop.remarks</code>. 备注信息
     */
    public LwShopRecord setRemarks(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_shop.remarks</code>. 备注信息
     */
    public String getRemarks() {
        return (String) get(3);
    }

    /**
     * Setter for <code>LW.lw_shop.del_flag</code>. 逻辑删除标记（0：显示；1：隐藏）
     */
    public LwShopRecord setDelFlag(UInteger value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_shop.del_flag</code>. 逻辑删除标记（0：显示；1：隐藏）
     */
    public UInteger getDelFlag() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>LW.lw_shop.name</code>. 店名
     */
    public LwShopRecord setName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_shop.name</code>. 店名
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>LW.lw_shop.address</code>. 地址
     */
    public LwShopRecord setAddress(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_shop.address</code>. 地址
     */
    public String getAddress() {
        return (String) get(6);
    }

    /**
     * Setter for <code>LW.lw_shop.contact_number</code>. 联系电话
     */
    public LwShopRecord setContactNumber(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>LW.lw_shop.contact_number</code>. 联系电话
     */
    public String getContactNumber() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Timestamp, Timestamp, String, UInteger, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Timestamp, Timestamp, String, UInteger, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return LwShop.LW_SHOP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return LwShop.LW_SHOP.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return LwShop.LW_SHOP.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return LwShop.LW_SHOP.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return LwShop.LW_SHOP.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return LwShop.LW_SHOP.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return LwShop.LW_SHOP.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return LwShop.LW_SHOP.CONTACT_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getContactNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwShopRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwShopRecord value2(Timestamp value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwShopRecord value3(Timestamp value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwShopRecord value4(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwShopRecord value5(UInteger value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwShopRecord value6(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwShopRecord value7(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwShopRecord value8(String value) {
        setContactNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LwShopRecord values(Long value1, Timestamp value2, Timestamp value3, String value4, UInteger value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LwShopRecord
     */
    public LwShopRecord() {
        super(LwShop.LW_SHOP);
    }

    /**
     * Create a detached, initialised LwShopRecord
     */
    public LwShopRecord(Long id, Timestamp createDate, Timestamp updateDate, String remarks, UInteger delFlag, String name, String address, String contactNumber) {
        super(LwShop.LW_SHOP);

        set(0, id);
        set(1, createDate);
        set(2, updateDate);
        set(3, remarks);
        set(4, delFlag);
        set(5, name);
        set(6, address);
        set(7, contactNumber);
    }
}
