/*
 * This file is generated by jOOQ.
*/
package com.java.src.lululu.business.domain;


import com.java.src.lululu.business.domain.tables.LwAccount;
import com.java.src.lululu.business.domain.tables.LwGoods;
import com.java.src.lululu.business.domain.tables.LwMember;
import com.java.src.lululu.business.domain.tables.LwMemberCard;
import com.java.src.lululu.business.domain.tables.LwOrder;
import com.java.src.lululu.business.domain.tables.LwShop;
import com.java.src.lululu.business.domain.tables.records.LwAccountRecord;
import com.java.src.lululu.business.domain.tables.records.LwGoodsRecord;
import com.java.src.lululu.business.domain.tables.records.LwMemberCardRecord;
import com.java.src.lululu.business.domain.tables.records.LwMemberRecord;
import com.java.src.lululu.business.domain.tables.records.LwOrderRecord;
import com.java.src.lululu.business.domain.tables.records.LwShopRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>LW</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<LwAccountRecord, Long> IDENTITY_LW_ACCOUNT = Identities0.IDENTITY_LW_ACCOUNT;
    public static final Identity<LwOrderRecord, Long> IDENTITY_LW_ORDER = Identities0.IDENTITY_LW_ORDER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LwAccountRecord> KEY_LW_ACCOUNT_PRIMARY = UniqueKeys0.KEY_LW_ACCOUNT_PRIMARY;
    public static final UniqueKey<LwGoodsRecord> KEY_LW_GOODS_PRIMARY = UniqueKeys0.KEY_LW_GOODS_PRIMARY;
    public static final UniqueKey<LwMemberRecord> KEY_LW_MEMBER_PRIMARY = UniqueKeys0.KEY_LW_MEMBER_PRIMARY;
    public static final UniqueKey<LwMemberCardRecord> KEY_LW_MEMBER_CARD_PRIMARY = UniqueKeys0.KEY_LW_MEMBER_CARD_PRIMARY;
    public static final UniqueKey<LwOrderRecord> KEY_LW_ORDER_PRIMARY = UniqueKeys0.KEY_LW_ORDER_PRIMARY;
    public static final UniqueKey<LwShopRecord> KEY_LW_SHOP_PRIMARY = UniqueKeys0.KEY_LW_SHOP_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<LwAccountRecord, Long> IDENTITY_LW_ACCOUNT = createIdentity(LwAccount.LW_ACCOUNT, LwAccount.LW_ACCOUNT.ID);
        public static Identity<LwOrderRecord, Long> IDENTITY_LW_ORDER = createIdentity(LwOrder.LW_ORDER, LwOrder.LW_ORDER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<LwAccountRecord> KEY_LW_ACCOUNT_PRIMARY = createUniqueKey(LwAccount.LW_ACCOUNT, "KEY_lw_account_PRIMARY", LwAccount.LW_ACCOUNT.ID);
        public static final UniqueKey<LwGoodsRecord> KEY_LW_GOODS_PRIMARY = createUniqueKey(LwGoods.LW_GOODS, "KEY_lw_goods_PRIMARY", LwGoods.LW_GOODS.ID);
        public static final UniqueKey<LwMemberRecord> KEY_LW_MEMBER_PRIMARY = createUniqueKey(LwMember.LW_MEMBER, "KEY_lw_member_PRIMARY", LwMember.LW_MEMBER.ID);
        public static final UniqueKey<LwMemberCardRecord> KEY_LW_MEMBER_CARD_PRIMARY = createUniqueKey(LwMemberCard.LW_MEMBER_CARD, "KEY_lw_member_card_PRIMARY", LwMemberCard.LW_MEMBER_CARD.ID);
        public static final UniqueKey<LwOrderRecord> KEY_LW_ORDER_PRIMARY = createUniqueKey(LwOrder.LW_ORDER, "KEY_lw_order_PRIMARY", LwOrder.LW_ORDER.ID);
        public static final UniqueKey<LwShopRecord> KEY_LW_SHOP_PRIMARY = createUniqueKey(LwShop.LW_SHOP, "KEY_lw_shop_PRIMARY", LwShop.LW_SHOP.ID);
    }
}
