/*
 * This file is generated by jOOQ.
*/
package com.java.src.lululu.business.domain;


import com.java.src.lululu.business.domain.tables.LwAccount;
import com.java.src.lululu.business.domain.tables.LwGoods;
import com.java.src.lululu.business.domain.tables.LwMember;
import com.java.src.lululu.business.domain.tables.LwMemberCard;
import com.java.src.lululu.business.domain.tables.LwOrder;
import com.java.src.lululu.business.domain.tables.LwShop;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lw extends SchemaImpl {

    private static final long serialVersionUID = -1717078842;

    /**
     * The reference instance of <code>LW</code>
     */
    public static final Lw LW = new Lw();

    /**
     * The table <code>LW.lw_account</code>.
     */
    public final LwAccount LW_ACCOUNT = com.java.src.lululu.business.domain.tables.LwAccount.LW_ACCOUNT;

    /**
     * The table <code>LW.lw_goods</code>.
     */
    public final LwGoods LW_GOODS = com.java.src.lululu.business.domain.tables.LwGoods.LW_GOODS;

    /**
     * The table <code>LW.lw_member</code>.
     */
    public final LwMember LW_MEMBER = com.java.src.lululu.business.domain.tables.LwMember.LW_MEMBER;

    /**
     * The table <code>LW.lw_member_card</code>.
     */
    public final LwMemberCard LW_MEMBER_CARD = com.java.src.lululu.business.domain.tables.LwMemberCard.LW_MEMBER_CARD;

    /**
     * The table <code>LW.lw_order</code>.
     */
    public final LwOrder LW_ORDER = com.java.src.lululu.business.domain.tables.LwOrder.LW_ORDER;

    /**
     * The table <code>LW.lw_shop</code>.
     */
    public final LwShop LW_SHOP = com.java.src.lululu.business.domain.tables.LwShop.LW_SHOP;

    /**
     * No further instances allowed
     */
    private Lw() {
        super("LW", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            LwAccount.LW_ACCOUNT,
            LwGoods.LW_GOODS,
            LwMember.LW_MEMBER,
            LwMemberCard.LW_MEMBER_CARD,
            LwOrder.LW_ORDER,
            LwShop.LW_SHOP);
    }
}
